### ISSUE TITLE
Plug-in Window has collapsed and cannot expand

### ISSUE THREAD

**Issue by pedrocs** [romannurik/Figma-Contrast#13]
I tied making the plug-in window smaller, but it collapsed on itself, and now I can't resize it back to the original size.

Window now looks like this:

<img width="655" alt="image" src="https://user-images.githubusercontent.com/852135/193629794-71911db2-5dff-486c-82b7-6535134b0fb4.png">

**Comment by matt-bailey** [comment]
I have a similar issue - I can only seem to make the window smaller, not bigger.

I'm using the desktop Mac App v116.4.4 (macOS Monterey).

![CleanShot 2022-11-10 at 09 13 00](https://user-images.githubusercontent.com/969385/201049965-15b88293-64fb-444e-997b-b5e83e16f04b.png)

**Comment by romannurik** [comment]
@pedrocs I think this was fixed with the latest release

@matt-bailey there's some known weirdness where if you quickly move the mouse outside the window it doesn't work (a known platform limitation) — but if you click and drag relatively slowly, does it work for you? (maybe i need to just remove resizing for now, as it's certainly finicky)

**Comment by matt-bailey** [comment]
Ah yes, If I drag the corner of the window slowly it works. Thanks

**Comment by pedrocs** [comment]
I managed to resize the window back to normal size, yes. Thank you!

**Comment by romannurik** [comment]
Dup of #15
